apiVersion: v1
kind: Pod
metadata:
  name: var-expansion-subpath-test
  labels:
    name: var-expansion-subpath-test
spec:
  containers:
  - name: dapi-container
    env:
    - name: POD_NAME
      value: /tmp

    image: e2eteam/busybox:1.29
    volumeMounts:
    - name: workdir1
      mountPath: /logscontainer
      subPathExpr: $(POD_NAME)
  restartPolicy: Never
  volumes:
    - name: workdir1
      emptyDir: {}
  nodeSelector:
    "kubernetes.io/hostname": 6226k8s001


