apiVersion: v1
kind: Pod
metadata:
  name: acceleratednetwork1
spec:
  containers:
  - name: test
    image: "mcr.microsoft.com/windows/servercore:1809"
    command: ["cmd"]
    args: ["/c","sleep","3600"]
    volumeMounts:
    - mountPath: "c:\\tools"
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: "c:\\tools"
      type: DirectoryOrCreate
  restartPolicy: Never
  nodeSelector:
    "kubernetes.io/hostname": "2916k8s001"


