apiVersion: v1
kind: Pod
metadata:
  name: acceleratednetwork0
spec:
  containers:
  - name: test
    image: "mcr.microsoft.com/windows/servercore:1809"
    command: ["cmd"]
    args: ["/c","dir","c:\\tools"]
    volumeMounts:
    - mountPath: "c:\\tools"
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: "c:\\tools"
      type: Directory
  restartPolicy: Never
  nodeSelector:
    "kubernetes.io/hostname": "2080k8s000"


